### ISSUE TITLE
PushViewController is not working

### ISSUE THREAD

**Issue by GaneshKumarSelvam** [KrishnaPatell/KPSmartTabBar#1]
How to navigate to other View controller in ButtonClick while Using KPSmarttabar,

[self.navigationController pushViewController:checkBalVC animated:YES]; is not working.

**Comment by KrishnaPatell** [comment]
Hello @GaneshKumarSelvam..
Sorry For the late reply..

I know your issue.
As we added Tab's view controllers as a child controller in main ViewController, that is why u cannot push your View Controller from child.

So you have 2 options.
1. You can implement **delegate** method, which will define your navigation code in Main view Controller and call it from your child controller. Just like **"refreshMe"** in my example code.

2. You can present your view controller from child controller.
